import NextTopLoader from 'nextjs-toploader';
export const metadata = {
  title: "AKSHAT | KNOW ABOUT ME",
  description: "Generated by create next app",
  icons:"logo.png"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <NextTopLoader color='#051e36' shadow="0 0 10px #051e36,0 0 5px #051e36" height={4} showSpinner={false}/>
        {children}
        </body>
    </html>
  );
}
